import LocalizedStrings from 'react-native-localization';

var l18n = new LocalizedStrings({
	en:{
		htitle: "Survey",
		loading: "Loading...",
		login: "Sign in",
		htitle: "SilverStripe SurveyManager",
		plogin: "Email",
		ppassword: "Password",
		autherror: "Unable to login",
		newsurvey: "New survey",
		startnew: "Start new survey?",
		start: "Start",
		cancel: "Cancel",
		ok: "OK",
		logout: "Log out",
		menu: "Menu",
		next: "Next",
		startsurvey:"Start survey",
		othervar:"Other variant",
		othershort:"Other",
		nexttocontinue:"Press > button to continue",
		nexttostart:"Press > button to start survey",
		syncmanual:"Sync manualy",
		surveyresults: "Survey results",
		totalanswers: "Total answers"},
	ru:{
		htitle: "Опрос",
		loading: "Загрузка...",
		login: "Войти",
		htitle: "SilverStripe SurveyManager",
		plogin: "Email",
		ppassword: "Пароль",
		autherror: "Не возможно зайти",
		newsurvey: "Новый опрос",
		startnew: "Начать новый опрос?",
		start: "Начать",
		cancel: "Отмена",
		ok: "OK",
		logout: "Выйти",
		menu: "Меню",
		next: "Дальше",
		startsurvey:"Начать опрос",
		othervar:"Другой вариант",
		othershort:"Дпугое",
		nexttocontinue:"Нажмите > чтобы продолжить",
		nexttostart:"Нажмите > чтобы начать опрос",
		syncmanual:"Синхронизировать",
		surveyresults: "Результаты опроса",
		totalanswers: "Всего ответов"},
		
  });

module.exports = l18n;
